export const helpUrls = {
  customerSupport: 'https://t.me/ProjectSerum',
  customerSupportZh: 'https://t.me/ProjectSerum_Chinese',
  contactEmail: 'mailto:contact@projectserum.com',
  discord: 'https://discord.gg/pandacoin',
  telegram: 'https://t.me/pandacoin_announcements',
  github: 'https://github.com/project-serum',
  projectSerum: 'https://projectserum.com/',
  developerResources: 'https://projectserum.com/developer-resources',
  solanaBeach: 'https://solanabeach.io',
  twitter: 'https://twitter.com/pandacoin_fi',
  website: 'https://www.pandacrypto.org/',
  medium: 'https://pandacoin-fi.medium.com/',
  listingForm: 'https://docs.google.com/forms/d/1l6LaedvKRlUBVq6BHj2X8vG_DyTXND4B5EflW2eO2Rs',
};
